<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Afghanistan',
                'code' => 'AF',
                'phone_code' => '+93',
                'currency' => 'Afghan Afghani',
                'currency_code' => 'AFN',
                'currency_symbol' => '؋',
                'flag' => '🇦🇫',
            ],
            [
                'name' => 'Albania',
                'code' => 'AL',
                'phone_code' => '+355',
                'currency' => 'Albanian Lek',
                'currency_code' => 'ALL',
                'currency_symbol' => 'L',
                'flag' => '🇦🇱',
            ],
            [
                'name' => 'Algeria',
                'code' => 'DZ',
                'phone_code' => '+213',
                'currency' => 'Algerian Dinar',
                'currency_code' => 'DZD',
                'currency_symbol' => 'دج',
                'flag' => '🇩🇿',
            ],
            [
                'name' => 'Andorra',
                'code' => 'AD',
                'phone_code' => '+376',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇦🇩',
            ],
            [
                'name' => 'Angola',
                'code' => 'AO',
                'phone_code' => '+244',
                'currency' => 'Angolan Kwanza',
                'currency_code' => 'AOA',
                'currency_symbol' => 'Kz',
                'flag' => '🇦🇴',
            ],
            [
                'name' => 'Antigua and Barbuda',
                'code' => 'AG',
                'phone_code' => '+1-268',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇦🇬',
            ],
            [
                'name' => 'Argentina',
                'code' => 'AR',
                'phone_code' => '+54',
                'currency' => 'Argentine Peso',
                'currency_code' => 'ARS',
                'currency_symbol' => '$',
                'flag' => '🇦🇷',
            ],
            [
                'name' => 'Armenia',
                'code' => 'AM',
                'phone_code' => '+374',
                'currency' => 'Armenian Dram',
                'currency_code' => 'AMD',
                'currency_symbol' => '֏',
                'flag' => '🇦🇲',
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'phone_code' => '+61',
                'currency' => 'Australian Dollar',
                'currency_code' => 'AUD',
                'currency_symbol' => '$',
                'flag' => '🇦🇺',
            ],
            [
                'name' => 'Austria',
                'code' => 'AT',
                'phone_code' => '+43',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇦🇹',
            ],
            [
                'name' => 'Azerbaijan',
                'code' => 'AZ',
                'phone_code' => '+994',
                'currency' => 'Azerbaijani Manat',
                'currency_code' => 'AZN',
                'currency_symbol' => '₼',
                'flag' => '🇦🇿',
            ],
            [
                'name' => 'Bahamas',
                'code' => 'BS',
                'phone_code' => '+1-242',
                'currency' => 'Bahamian Dollar',
                'currency_code' => 'BSD',
                'currency_symbol' => '$',
                'flag' => '🇧🇸',
            ],
            [
                'name' => 'Bahrain',
                'code' => 'BH',
                'phone_code' => '+973',
                'currency' => 'Bahraini Dinar',
                'currency_code' => 'BHD',
                'currency_symbol' => '.د.ب',
                'flag' => '🇧🇭',
            ],
            [
                'name' => 'Bangladesh',
                'code' => 'BD',
                'phone_code' => '+880',
                'currency' => 'Bangladeshi Taka',
                'currency_code' => 'BDT',
                'currency_symbol' => '৳',
                'flag' => '🇧🇩',
            ],
            [
                'name' => 'Barbados',
                'code' => 'BB',
                'phone_code' => '+1-246',
                'currency' => 'Barbadian Dollar',
                'currency_code' => 'BBD',
                'currency_symbol' => '$',
                'flag' => '🇧🇧',
            ],
            [
                'name' => 'Belarus',
                'code' => 'BY',
                'phone_code' => '+375',
                'currency' => 'Belarusian Ruble',
                'currency_code' => 'BYN',
                'currency_symbol' => 'Br',
                'flag' => '🇧🇾',
            ],
            [
                'name' => 'Belgium',
                'code' => 'BE',
                'phone_code' => '+32',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇧🇪',
            ],
            [
                'name' => 'Belize',
                'code' => 'BZ',
                'phone_code' => '+501',
                'currency' => 'Belize Dollar',
                'currency_code' => 'BZD',
                'currency_symbol' => '$',
                'flag' => '🇧🇿',
            ],
            [
                'name' => 'Benin',
                'code' => 'BJ',
                'phone_code' => '+229',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇧🇯',
            ],
            [
                'name' => 'Bhutan',
                'code' => 'BT',
                'phone_code' => '+975',
                'currency' => 'Bhutanese Ngultrum',
                'currency_code' => 'BTN',
                'currency_symbol' => 'Nu.',
                'flag' => '🇧🇹',
            ],
            [
                'name' => 'Bolivia',
                'code' => 'BO',
                'phone_code' => '+591',
                'currency' => 'Bolivian Boliviano',
                'currency_code' => 'BOB',
                'currency_symbol' => 'Bs.',
                'flag' => '🇧🇴',
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'code' => 'BA',
                'phone_code' => '+387',
                'currency' => 'Bosnia and Herzegovina Convertible Mark',
                'currency_code' => 'BAM',
                'currency_symbol' => 'KM',
                'flag' => '🇧🇦',
            ],
            [
                'name' => 'Botswana',
                'code' => 'BW',
                'phone_code' => '+267',
                'currency' => 'Botswana Pula',
                'currency_code' => 'BWP',
                'currency_symbol' => 'P',
                'flag' => '🇧🇼',
            ],
            [
                'name' => 'Brazil',
                'code' => 'BR',
                'phone_code' => '+55',
                'currency' => 'Brazilian Real',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'flag' => '🇧🇷',
            ],
            [
                'name' => 'Brunei',
                'code' => 'BN',
                'phone_code' => '+673',
                'currency' => 'Brunei Dollar',
                'currency_code' => 'BND',
                'currency_symbol' => '$',
                'flag' => '🇧🇳',
            ],
            [
                'name' => 'Bulgaria',
                'code' => 'BG',
                'phone_code' => '+359',
                'currency' => 'Bulgarian Lev',
                'currency_code' => 'BGN',
                'currency_symbol' => 'лв',
                'flag' => '🇧🇬',
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'phone_code' => '+226',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇧🇫',
            ],
            [
                'name' => 'Burundi',
                'code' => 'BI',
                'phone_code' => '+257',
                'currency' => 'Burundian Franc',
                'currency_code' => 'BIF',
                'currency_symbol' => 'FBu',
                'flag' => '🇧🇮',
            ],
            [
                'name' => 'Cabo Verde',
                'code' => 'CV',
                'phone_code' => '+238',
                'currency' => 'Cape Verdean Escudo',
                'currency_code' => 'CVE',
                'currency_symbol' => '$',
                'flag' => '🇨🇻',
            ],
            [
                'name' => 'Cambodia',
                'code' => 'KH',
                'phone_code' => '+855',
                'currency' => 'Cambodian Riel',
                'currency_code' => 'KHR',
                'currency_symbol' => '៛',
                'flag' => '🇰🇭',
            ],
            [
                'name' => 'Cameroon',
                'code' => 'CM',
                'phone_code' => '+237',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇨🇲',
            ],
            [
                'name' => 'Canada',
                'code' => 'CA',
                'phone_code' => '+1',
                'currency' => 'Canadian Dollar',
                'currency_code' => 'CAD',
                'currency_symbol' => '$',
                'flag' => '🇨🇦',
            ],
            [
                'name' => 'Central African Republic',
                'code' => 'CF',
                'phone_code' => '+236',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇨🇫',
            ],
            [
                'name' => 'Chad',
                'code' => 'TD',
                'phone_code' => '+235',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇹🇩',
            ],
            [
                'name' => 'Chile',
                'code' => 'CL',
                'phone_code' => '+56',
                'currency' => 'Chilean Peso',
                'currency_code' => 'CLP',
                'currency_symbol' => '$',
                'flag' => '🇨🇱',
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'phone_code' => '+86',
                'currency' => 'Chinese Yuan',
                'currency_code' => 'CNY',
                'currency_symbol' => '¥',
                'flag' => '🇨🇳',
            ],
            [
                'name' => 'Colombia',
                'code' => 'CO',
                'phone_code' => '+57',
                'currency' => 'Colombian Peso',
                'currency_code' => 'COP',
                'currency_symbol' => '$',
                'flag' => '🇨🇴',
            ],
            [
                'name' => 'Comoros',
                'code' => 'KM',
                'phone_code' => '+269',
                'currency' => 'Comorian Franc',
                'currency_code' => 'KMF',
                'currency_symbol' => 'CF',
                'flag' => '🇰🇲',
            ],
            [
                'name' => 'Congo (Congo-Brazzaville)',
                'code' => 'CG',
                'phone_code' => '+242',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇨🇬',
            ],
            [
                'name' => 'Congo (Congo-Kinshasa)',
                'code' => 'CD',
                'phone_code' => '+243',
                'currency' => 'Congolese Franc',
                'currency_code' => 'CDF',
                'currency_symbol' => 'FC',
                'flag' => '🇨🇩',
            ],
            [
                'name' => 'Costa Rica',
                'code' => 'CR',
                'phone_code' => '+506',
                'currency' => 'Costa Rican Colón',
                'currency_code' => 'CRC',
                'currency_symbol' => '₡',
                'flag' => '🇨🇷',
            ],
            [
                'name' => 'Croatia',
                'code' => 'HR',
                'phone_code' => '+385',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇭🇷',
            ],
            [
                'name' => 'Cuba',
                'code' => 'CU',
                'phone_code' => '+53',
                'currency' => 'Cuban Peso',
                'currency_code' => 'CUP',
                'currency_symbol' => '$',
                'flag' => '🇨🇺',
            ],
            [
                'name' => 'Cyprus',
                'code' => 'CY',
                'phone_code' => '+357',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇨🇾',
            ],
            [
                'name' => 'Czechia',
                'code' => 'CZ',
                'phone_code' => '+420',
                'currency' => 'Czech Koruna',
                'currency_code' => 'CZK',
                'currency_symbol' => 'Kč',
                'flag' => '🇨🇿',
            ],
            [
                'name' => 'Denmark',
                'code' => 'DK',
                'phone_code' => '+45',
                'currency' => 'Danish Krone',
                'currency_code' => 'DKK',
                'currency_symbol' => 'kr',
                'flag' => '🇩🇰',
            ],
            [
                'name' => 'Djibouti',
                'code' => 'DJ',
                'phone_code' => '+253',
                'currency' => 'Djiboutian Franc',
                'currency_code' => 'DJF',
                'currency_symbol' => 'Fdj',
                'flag' => '🇩🇯',
            ],
            [
                'name' => 'Dominica',
                'code' => 'DM',
                'phone_code' => '+1-767',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇩🇲',
            ],
            [
                'name' => 'Dominican Republic',
                'code' => 'DO',
                'phone_code' => '+1-809',
                'currency' => 'Dominican Peso',
                'currency_code' => 'DOP',
                'currency_symbol' => 'RD$',
                'flag' => '🇩🇴',
            ],
            [
                'name' => 'Ecuador',
                'code' => 'EC',
                'phone_code' => '+593',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇪🇨',
            ],
            [
                'name' => 'Egypt',
                'code' => 'EG',
                'phone_code' => '+20',
                'currency' => 'Egyptian Pound',
                'currency_code' => 'EGP',
                'currency_symbol' => '£',
                'flag' => '🇪🇬',
            ],
            [
                'name' => 'El Salvador',
                'code' => 'SV',
                'phone_code' => '+503',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇸🇻',
            ],
            [
                'name' => 'Equatorial Guinea',
                'code' => 'GQ',
                'phone_code' => '+240',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇬🇶',
            ],
            [
                'name' => 'Eritrea',
                'code' => 'ER',
                'phone_code' => '+291',
                'currency' => 'Eritrean Nakfa',
                'currency_code' => 'ERN',
                'currency_symbol' => 'Nfk',
                'flag' => '🇪🇷',
            ],
            [
                'name' => 'Estonia',
                'code' => 'EE',
                'phone_code' => '+372',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇪🇪',
            ],
            [
                'name' => 'Eswatini',
                'code' => 'SZ',
                'phone_code' => '+268',
                'currency' => 'Swazi Lilangeni',
                'currency_code' => 'SZL',
                'currency_symbol' => 'E',
                'flag' => '🇸🇿',
            ],
            [
                'name' => 'Ethiopia',
                'code' => 'ET',
                'phone_code' => '+251',
                'currency' => 'Ethiopian Birr',
                'currency_code' => 'ETB',
                'currency_symbol' => 'Br',
                'flag' => '🇪🇹',
            ],
            [
                'name' => 'Fiji',
                'code' => 'FJ',
                'phone_code' => '+679',
                'currency' => 'Fijian Dollar',
                'currency_code' => 'FJD',
                'currency_symbol' => '$',
                'flag' => '🇫🇯',
            ],
            [
                'name' => 'Finland',
                'code' => 'FI',
                'phone_code' => '+358',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇫🇮',
            ],
            [
                'name' => 'France',
                'code' => 'FR',
                'phone_code' => '+33',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇫🇷',
            ],
            [
                'name' => 'Gabon',
                'code' => 'GA',
                'phone_code' => '+241',
                'currency' => 'Central African CFA franc',
                'currency_code' => 'XAF',
                'currency_symbol' => 'CFA',
                'flag' => '🇬🇦',
            ],
            [
                'name' => 'Gambia',
                'code' => 'GM',
                'phone_code' => '+220',
                'currency' => 'Gambian Dalasi',
                'currency_code' => 'GMD',
                'currency_symbol' => 'D',
                'flag' => '🇬🇲',
            ],
            [
                'name' => 'Georgia',
                'code' => 'GE',
                'phone_code' => '+995',
                'currency' => 'Georgian Lari',
                'currency_code' => 'GEL',
                'currency_symbol' => '₾',
                'flag' => '🇬🇪',
            ],
            [
                'name' => 'Germany',
                'code' => 'DE',
                'phone_code' => '+49',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇩🇪',
            ],
            [
                'name' => 'Ghana',
                'code' => 'GH',
                'phone_code' => '+233',
                'currency' => 'Ghanaian Cedi',
                'currency_code' => 'GHS',
                'currency_symbol' => '₵',
                'flag' => '🇬🇭',
            ],
            [
                'name' => 'Greece',
                'code' => 'GR',
                'phone_code' => '+30',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇬🇷',
            ],
            [
                'name' => 'Grenada',
                'code' => 'GD',
                'phone_code' => '+1-473',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇬🇩',
            ],
            [
                'name' => 'Guatemala',
                'code' => 'GT',
                'phone_code' => '+502',
                'currency' => 'Guatemalan Quetzal',
                'currency_code' => 'GTQ',
                'currency_symbol' => 'Q',
                'flag' => '🇬🇹',
            ],
            [
                'name' => 'Guinea',
                'code' => 'GN',
                'phone_code' => '+224',
                'currency' => 'Guinean Franc',
                'currency_code' => 'GNF',
                'currency_symbol' => 'FG',
                'flag' => '🇬🇳',
            ],
            [
                'name' => 'Guinea-Bissau',
                'code' => 'GW',
                'phone_code' => '+245',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇬🇼',
            ],
            [
                'name' => 'Guyana',
                'code' => 'GY',
                'phone_code' => '+592',
                'currency' => 'Guyanese Dollar',
                'currency_code' => 'GYD',
                'currency_symbol' => '$',
                'flag' => '🇬🇾',
            ],
            [
                'name' => 'Haiti',
                'code' => 'HT',
                'phone_code' => '+509',
                'currency' => 'Haitian Gourde',
                'currency_code' => 'HTG',
                'currency_symbol' => 'G',
                'flag' => '🇭🇹',
            ],
            [
                'name' => 'Honduras',
                'code' => 'HN',
                'phone_code' => '+504',
                'currency' => 'Honduran Lempira',
                'currency_code' => 'HNL',
                'currency_symbol' => 'L',
                'flag' => '🇭🇳',
            ],
            [
                'name' => 'Hungary',
                'code' => 'HU',
                'phone_code' => '+36',
                'currency' => 'Hungarian Forint',
                'currency_code' => 'HUF',
                'currency_symbol' => 'Ft',
                'flag' => '🇭🇺',
            ],
            [
                'name' => 'Iceland',
                'code' => 'IS',
                'phone_code' => '+354',
                'currency' => 'Icelandic Króna',
                'currency_code' => 'ISK',
                'currency_symbol' => 'kr',
                'flag' => '🇮🇸',
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'phone_code' => '+91',
                'currency' => 'Indian Rupee',
                'currency_code' => 'INR',
                'currency_symbol' => '₹',
                'flag' => '🇮🇳',
            ],
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'phone_code' => '+62',
                'currency' => 'Indonesian Rupiah',
                'currency_code' => 'IDR',
                'currency_symbol' => 'Rp',
                'flag' => '🇮🇩',
            ],
            [
                'name' => 'Iran',
                'code' => 'IR',
                'phone_code' => '+98',
                'currency' => 'Iranian Rial',
                'currency_code' => 'IRR',
                'currency_symbol' => '﷼',
                'flag' => '🇮🇷',
            ],
            [
                'name' => 'Iraq',
                'code' => 'IQ',
                'phone_code' => '+964',
                'currency' => 'Iraqi Dinar',
                'currency_code' => 'IQD',
                'currency_symbol' => 'ع.د',
                'flag' => '🇮🇶',
            ],
            [
                'name' => 'Ireland',
                'code' => 'IE',
                'phone_code' => '+353',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇮🇪',
            ],
            [
                'name' => 'Israel',
                'code' => 'IL',
                'phone_code' => '+972',
                'currency' => 'Israeli New Shekel',
                'currency_code' => 'ILS',
                'currency_symbol' => '₪',
                'flag' => '🇮🇱',
            ],
            [
                'name' => 'Italy',
                'code' => 'IT',
                'phone_code' => '+39',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇮🇹',
            ],
            [
                'name' => 'Jamaica',
                'code' => 'JM',
                'phone_code' => '+1-876',
                'currency' => 'Jamaican Dollar',
                'currency_code' => 'JMD',
                'currency_symbol' => 'J$',
                'flag' => '🇯🇲',
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'phone_code' => '+81',
                'currency' => 'Japanese Yen',
                'currency_code' => 'JPY',
                'currency_symbol' => '¥',
                'flag' => '🇯🇵',
            ],
            [
                'name' => 'Jordan',
                'code' => 'JO',
                'phone_code' => '+962',
                'currency' => 'Jordanian Dinar',
                'currency_code' => 'JOD',
                'currency_symbol' => 'د.ا',
                'flag' => '🇯🇴',
            ],
            [
                'name' => 'Kazakhstan',
                'code' => 'KZ',
                'phone_code' => '+7',
                'currency' => 'Kazakhstani Tenge',
                'currency_code' => 'KZT',
                'currency_symbol' => '₸',
                'flag' => '🇰🇿',
            ],
            [
                'name' => 'Kenya',
                'code' => 'KE',
                'phone_code' => '+254',
                'currency' => 'Kenyan Shilling',
                'currency_code' => 'KES',
                'currency_symbol' => 'KSh',
                'flag' => '🇰🇪',
            ],
            [
                'name' => 'Kiribati',
                'code' => 'KI',
                'phone_code' => '+686',
                'currency' => 'Australian Dollar',
                'currency_code' => 'AUD',
                'currency_symbol' => '$',
                'flag' => '🇰🇮',
            ],
            [
                'name' => 'Kuwait',
                'code' => 'KW',
                'phone_code' => '+965',
                'currency' => 'Kuwaiti Dinar',
                'currency_code' => 'KWD',
                'currency_symbol' => 'د.ك',
                'flag' => '🇰🇼',
            ],
            [
                'name' => 'Kyrgyzstan',
                'code' => 'KG',
                'phone_code' => '+996',
                'currency' => 'Kyrgyzstani Som',
                'currency_code' => 'KGS',
                'currency_symbol' => 'с',
                'flag' => '🇰🇬',
            ],
            [
                'name' => 'Laos',
                'code' => 'LA',
                'phone_code' => '+856',
                'currency' => 'Lao Kip',
                'currency_code' => 'LAK',
                'currency_symbol' => '₭',
                'flag' => '🇱🇦',
            ],
            [
                'name' => 'Latvia',
                'code' => 'LV',
                'phone_code' => '+371',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇱🇻',
            ],
            [
                'name' => 'Lebanon',
                'code' => 'LB',
                'phone_code' => '+961',
                'currency' => 'Lebanese Pound',
                'currency_code' => 'LBP',
                'currency_symbol' => 'ل.ل',
                'flag' => '🇱🇧',
            ],
            [
                'name' => 'Lesotho',
                'code' => 'LS',
                'phone_code' => '+266',
                'currency' => 'Lesotho Loti',
                'currency_code' => 'LSL',
                'currency_symbol' => 'L',
                'flag' => '🇱🇸',
            ],
            [
                'name' => 'Liberia',
                'code' => 'LR',
                'phone_code' => '+231',
                'currency' => 'Liberian Dollar',
                'currency_code' => 'LRD',
                'currency_symbol' => '$',
                'flag' => '🇱🇷',
            ],
            [
                'name' => 'Libya',
                'code' => 'LY',
                'phone_code' => '+218',
                'currency' => 'Libyan Dinar',
                'currency_code' => 'LYD',
                'currency_symbol' => 'ل.د',
                'flag' => '🇱🇾',
            ],
            [
                'name' => 'Liechtenstein',
                'code' => 'LI',
                'phone_code' => '+423',
                'currency' => 'Swiss Franc',
                'currency_code' => 'CHF',
                'currency_symbol' => 'Fr.',
                'flag' => '🇱🇮',
            ],
            [
                'name' => 'Lithuania',
                'code' => 'LT',
                'phone_code' => '+370',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇱🇹',
            ],
            [
                'name' => 'Luxembourg',
                'code' => 'LU',
                'phone_code' => '+352',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇱🇺',
            ],
            [
                'name' => 'Madagascar',
                'code' => 'MG',
                'phone_code' => '+261',
                'currency' => 'Malagasy Ariary',
                'currency_code' => 'MGA',
                'currency_symbol' => 'Ar',
                'flag' => '🇲🇬',
            ],
            [
                'name' => 'Malawi',
                'code' => 'MW',
                'phone_code' => '+265',
                'currency' => 'Malawian Kwacha',
                'currency_code' => 'MWK',
                'currency_symbol' => 'MK',
                'flag' => '🇲🇼',
            ],
            [
                'name' => 'Malaysia',
                'code' => 'MY',
                'phone_code' => '+60',
                'currency' => 'Malaysian Ringgit',
                'currency_code' => 'MYR',
                'currency_symbol' => 'RM',
                'flag' => '🇲🇾',
            ],
            [
                'name' => 'Maldives',
                'code' => 'MV',
                'phone_code' => '+960',
                'currency' => 'Maldivian Rufiyaa',
                'currency_code' => 'MVR',
                'currency_symbol' => 'Rf',
                'flag' => '🇲🇻',
            ],
            [
                'name' => 'Mali',
                'code' => 'ML',
                'phone_code' => '+223',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇲🇱',
            ],
            [
                'name' => 'Malta',
                'code' => 'MT',
                'phone_code' => '+356',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇲🇹',
            ],
            [
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'phone_code' => '+692',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇲🇭',
            ],
            [
                'name' => 'Mauritania',
                'code' => 'MR',
                'phone_code' => '+222',
                'currency' => 'Mauritanian Ouguiya',
                'currency_code' => 'MRU',
                'currency_symbol' => 'UM',
                'flag' => '🇲🇷',
            ],
            [
                'name' => 'Mauritius',
                'code' => 'MU',
                'phone_code' => '+230',
                'currency' => 'Mauritian Rupee',
                'currency_code' => 'MUR',
                'currency_symbol' => '₨',
                'flag' => '🇲🇺',
            ],
            [
                'name' => 'Mexico',
                'code' => 'MX',
                'phone_code' => '+52',
                'currency' => 'Mexican Peso',
                'currency_code' => 'MXN',
                'currency_symbol' => '$',
                'flag' => '🇲🇽',
            ],
            [
                'name' => 'Micronesia',
                'code' => 'FM',
                'phone_code' => '+691',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇫🇲',
            ],
            [
                'name' => 'Moldova',
                'code' => 'MD',
                'phone_code' => '+373',
                'currency' => 'Moldovan Leu',
                'currency_code' => 'MDL',
                'currency_symbol' => 'L',
                'flag' => '🇲🇩',
            ],
            [
                'name' => 'Monaco',
                'code' => 'MC',
                'phone_code' => '+377',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇲🇨',
            ],
            [
                'name' => 'Mongolia',
                'code' => 'MN',
                'phone_code' => '+976',
                'currency' => 'Mongolian Tögrög',
                'currency_code' => 'MNT',
                'currency_symbol' => '₮',
                'flag' => '🇲🇳',
            ],
            [
                'name' => 'Montenegro',
                'code' => 'ME',
                'phone_code' => '+382',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇲🇪',
            ],
            [
                'name' => 'Morocco',
                'code' => 'MA',
                'phone_code' => '+212',
                'currency' => 'Moroccan Dirham',
                'currency_code' => 'MAD',
                'currency_symbol' => 'د.م.',
                'flag' => '🇲🇦',
            ],
            [
                'name' => 'Mozambique',
                'code' => 'MZ',
                'phone_code' => '+258',
                'currency' => 'Mozambican Metical',
                'currency_code' => 'MZN',
                'currency_symbol' => 'MT',
                'flag' => '🇲🇿',
            ],
            [
                'name' => 'Myanmar',
                'code' => 'MM',
                'phone_code' => '+95',
                'currency' => 'Burmese Kyat',
                'currency_code' => 'MMK',
                'currency_symbol' => 'K',
                'flag' => '🇲🇲',
            ],
            [
                'name' => 'Namibia',
                'code' => 'NA',
                'phone_code' => '+264',
                'currency' => 'Namibian Dollar',
                'currency_code' => 'NAD',
                'currency_symbol' => '$',
                'flag' => '🇳🇦',
            ],
            [
                'name' => 'Nauru',
                'code' => 'NR',
                'phone_code' => '+674',
                'currency' => 'Australian Dollar',
                'currency_code' => 'AUD',
                'currency_symbol' => '$',
                'flag' => '🇳🇷',
            ],
            [
                'name' => 'Nepal',
                'code' => 'NP',
                'phone_code' => '+977',
                'currency' => 'Nepalese Rupee',
                'currency_code' => 'NPR',
                'currency_symbol' => '₨',
                'flag' => '🇳🇵',
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NL',
                'phone_code' => '+31',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇳🇱',
            ],
            [
                'name' => 'New Zealand',
                'code' => 'NZ',
                'phone_code' => '+64',
                'currency' => 'New Zealand Dollar',
                'currency_code' => 'NZD',
                'currency_symbol' => '$',
                'flag' => '🇳🇿',
            ],
            [
                'name' => 'Nicaragua',
                'code' => 'NI',
                'phone_code' => '+505',
                'currency' => 'Nicaraguan Córdoba',
                'currency_code' => 'NIO',
                'currency_symbol' => 'C$',
                'flag' => '🇳🇮',
            ],
            [
                'name' => 'Niger',
                'code' => 'NE',
                'phone_code' => '+227',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇳🇪',
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NG',
                'phone_code' => '+234',
                'currency' => 'Nigerian Naira',
                'currency_code' => 'NGN',
                'currency_symbol' => '₦',
                'flag' => '🇳🇬',
            ],
            [
                'name' => 'North Korea',
                'code' => 'KP',
                'phone_code' => '+850',
                'currency' => 'North Korean Won',
                'currency_code' => 'KPW',
                'currency_symbol' => '₩',
                'flag' => '🇰🇵',
            ],
            [
                'name' => 'North Macedonia',
                'code' => 'MK',
                'phone_code' => '+389',
                'currency' => 'Macedonian Denar',
                'currency_code' => 'MKD',
                'currency_symbol' => 'ден',
                'flag' => '🇲🇰',
            ],
            [
                'name' => 'Norway',
                'code' => 'NO',
                'phone_code' => '+47',
                'currency' => 'Norwegian Krone',
                'currency_code' => 'NOK',
                'currency_symbol' => 'kr',
                'flag' => '🇳🇴',
            ],
            [
                'name' => 'Oman',
                'code' => 'OM',
                'phone_code' => '+968',
                'currency' => 'Omani Rial',
                'currency_code' => 'OMR',
                'currency_symbol' => 'ر.ع.',
                'flag' => '🇴🇲',
            ],
            [
                'name' => 'Pakistan',
                'code' => 'PK',
                'phone_code' => '+92',
                'currency' => 'Pakistani Rupee',
                'currency_code' => 'PKR',
                'currency_symbol' => '₨',
                'flag' => '🇵🇰',
            ],
            [
                'name' => 'Palau',
                'code' => 'PW',
                'phone_code' => '+680',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇵🇼',
            ],
            [
                'name' => 'Palestine',
                'code' => 'PS',
                'phone_code' => '+970',
                'currency' => 'Israeli New Shekel',
                'currency_code' => 'ILS',
                'currency_symbol' => '₪',
                'flag' => '🇵🇸',
            ],
            [
                'name' => 'Panama',
                'code' => 'PA',
                'phone_code' => '+507',
                'currency' => 'Panamanian Balboa',
                'currency_code' => 'PAB',
                'currency_symbol' => 'B/.',
                'flag' => '🇵🇦',
            ],
            [
                'name' => 'Papua New Guinea',
                'code' => 'PG',
                'phone_code' => '+675',
                'currency' => 'Papua New Guinean Kina',
                'currency_code' => 'PGK',
                'currency_symbol' => 'K',
                'flag' => '🇵🇬',
            ],
            [
                'name' => 'Paraguay',
                'code' => 'PY',
                'phone_code' => '+595',
                'currency' => 'Paraguayan Guaraní',
                'currency_code' => 'PYG',
                'currency_symbol' => '₲',
                'flag' => '🇵🇾',
            ],
            [
                'name' => 'Peru',
                'code' => 'PE',
                'phone_code' => '+51',
                'currency' => 'Peruvian Sol',
                'currency_code' => 'PEN',
                'currency_symbol' => 'S/',
                'flag' => '🇵🇪',
            ],
            [
                'name' => 'Philippines',
                'code' => 'PH',
                'phone_code' => '+63',
                'currency' => 'Philippine Peso',
                'currency_code' => 'PHP',
                'currency_symbol' => '₱',
                'flag' => '🇵🇭',
            ],
            [
                'name' => 'Poland',
                'code' => 'PL',
                'phone_code' => '+48',
                'currency' => 'Polish Złoty',
                'currency_code' => 'PLN',
                'currency_symbol' => 'zł',
                'flag' => '🇵🇱',
            ],
            [
                'name' => 'Portugal',
                'code' => 'PT',
                'phone_code' => '+351',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇵🇹',
            ],
            [
                'name' => 'Qatar',
                'code' => 'QA',
                'phone_code' => '+974',
                'currency' => 'Qatari Riyal',
                'currency_code' => 'QAR',
                'currency_symbol' => 'ر.ق',
                'flag' => '🇶🇦',
            ],
            [
                'name' => 'Romania',
                'code' => 'RO',
                'phone_code' => '+40',
                'currency' => 'Romanian Leu',
                'currency_code' => 'RON',
                'currency_symbol' => 'lei',
                'flag' => '🇷🇴',
            ],
            [
                'name' => 'Russia',
                'code' => 'RU',
                'phone_code' => '+7',
                'currency' => 'Russian Ruble',
                'currency_code' => 'RUB',
                'currency_symbol' => '₽',
                'flag' => '🇷🇺',
            ],
            [
                'name' => 'Rwanda',
                'code' => 'RW',
                'phone_code' => '+250',
                'currency' => 'Rwandan Franc',
                'currency_code' => 'RWF',
                'currency_symbol' => 'FRw',
                'flag' => '🇷🇼',
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'code' => 'KN',
                'phone_code' => '+1-869',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇰🇳',
            ],
            [
                'name' => 'Saint Lucia',
                'code' => 'LC',
                'phone_code' => '+1-758',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇱🇨',
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'code' => 'VC',
                'phone_code' => '+1-784',
                'currency' => 'East Caribbean Dollar',
                'currency_code' => 'XCD',
                'currency_symbol' => '$',
                'flag' => '🇻🇨',
            ],
            [
                'name' => 'Samoa',
                'code' => 'WS',
                'phone_code' => '+685',
                'currency' => 'Samoan Tala',
                'currency_code' => 'WST',
                'currency_symbol' => 'T',
                'flag' => '🇼🇸',
            ],
            [
                'name' => 'San Marino',
                'code' => 'SM',
                'phone_code' => '+378',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇸🇲',
            ],
            [
                'name' => 'Sao Tome and Principe',
                'code' => 'ST',
                'phone_code' => '+239',
                'currency' => 'São Tomé and Príncipe Dobra',
                'currency_code' => 'STN',
                'currency_symbol' => 'Db',
                'flag' => '🇸🇹',
            ],
            [
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'phone_code' => '+966',
                'currency' => 'Saudi Riyal',
                'currency_code' => 'SAR',
                'currency_symbol' => 'ر.س',
                'flag' => '🇸🇦',
            ],
            [
                'name' => 'Senegal',
                'code' => 'SN',
                'phone_code' => '+221',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇸🇳',
            ],
            [
                'name' => 'Serbia',
                'code' => 'RS',
                'phone_code' => '+381',
                'currency' => 'Serbian Dinar',
                'currency_code' => 'RSD',
                'currency_symbol' => 'дин',
                'flag' => '🇷🇸',
            ],
            [
                'name' => 'Seychelles',
                'code' => 'SC',
                'phone_code' => '+248',
                'currency' => 'Seychellois Rupee',
                'currency_code' => 'SCR',
                'currency_symbol' => '₨',
                'flag' => '🇸🇨',
            ],
            [
                'name' => 'Sierra Leone',
                'code' => 'SL',
                'phone_code' => '+232',
                'currency' => 'Sierra Leonean Leone',
                'currency_code' => 'SLL',
                'currency_symbol' => 'Le',
                'flag' => '🇸🇱',
            ],
            [
                'name' => 'Singapore',
                'code' => 'SG',
                'phone_code' => '+65',
                'currency' => 'Singapore Dollar',
                'currency_code' => 'SGD',
                'currency_symbol' => '$',
                'flag' => '🇸🇬',
            ],
            [
                'name' => 'Slovakia',
                'code' => 'SK',
                'phone_code' => '+421',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇸🇰',
            ],
            [
                'name' => 'Slovenia',
                'code' => 'SI',
                'phone_code' => '+386',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇸🇮',
            ],
            [
                'name' => 'Solomon Islands',
                'code' => 'SB',
                'phone_code' => '+677',
                'currency' => 'Solomon Islands Dollar',
                'currency_code' => 'SBD',
                'currency_symbol' => '$',
                'flag' => '🇸🇧',
            ],
            [
                'name' => 'Somalia',
                'code' => 'SO',
                'phone_code' => '+252',
                'currency' => 'Somali Shilling',
                'currency_code' => 'SOS',
                'currency_symbol' => 'Sh',
                'flag' => '🇸🇴',
            ],
            [
                'name' => 'South Africa',
                'code' => 'ZA',
                'phone_code' => '+27',
                'currency' => 'South African Rand',
                'currency_code' => 'ZAR',
                'currency_symbol' => 'R',
                'flag' => '🇿🇦',
            ],
            [
                'name' => 'South Korea',
                'code' => 'KR',
                'phone_code' => '+82',
                'currency' => 'South Korean Won',
                'currency_code' => 'KRW',
                'currency_symbol' => '₩',
                'flag' => '🇰🇷',
            ],
            [
                'name' => 'South Sudan',
                'code' => 'SS',
                'phone_code' => '+211',
                'currency' => 'South Sudanese Pound',
                'currency_code' => 'SSP',
                'currency_symbol' => '£',
                'flag' => '🇸🇸',
            ],
            [
                'name' => 'Spain',
                'code' => 'ES',
                'phone_code' => '+34',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇪🇸',
            ],
            [
                'name' => 'Sri Lanka',
                'code' => 'LK',
                'phone_code' => '+94',
                'currency' => 'Sri Lankan Rupee',
                'currency_code' => 'LKR',
                'currency_symbol' => '₨',
                'flag' => '🇱🇰',
            ],
            [
                'name' => 'Sudan',
                'code' => 'SD',
                'phone_code' => '+249',
                'currency' => 'Sudanese Pound',
                'currency_code' => 'SDG',
                'currency_symbol' => 'ج.س.',
                'flag' => '🇸🇩',
            ],
            [
                'name' => 'Suriname',
                'code' => 'SR',
                'phone_code' => '+597',
                'currency' => 'Surinamese Dollar',
                'currency_code' => 'SRD',
                'currency_symbol' => '$',
                'flag' => '🇸🇷',
            ],
            [
                'name' => 'Sweden',
                'code' => 'SE',
                'phone_code' => '+46',
                'currency' => 'Swedish Krona',
                'currency_code' => 'SEK',
                'currency_symbol' => 'kr',
                'flag' => '🇸🇪',
            ],
            [
                'name' => 'Switzerland',
                'code' => 'CH',
                'phone_code' => '+41',
                'currency' => 'Swiss Franc',
                'currency_code' => 'CHF',
                'currency_symbol' => 'Fr.',
                'flag' => '🇨🇭',
            ],
            [
                'name' => 'Syria',
                'code' => 'SY',
                'phone_code' => '+963',
                'currency' => 'Syrian Pound',
                'currency_code' => 'SYP',
                'currency_symbol' => '£',
                'flag' => '🇸🇾',
            ],
            [
                'name' => 'Taiwan',
                'code' => 'TW',
                'phone_code' => '+886',
                'currency' => 'New Taiwan Dollar',
                'currency_code' => 'TWD',
                'currency_symbol' => 'NT$',
                'flag' => '🇹🇼',
            ],
            [
                'name' => 'Tajikistan',
                'code' => 'TJ',
                'phone_code' => '+992',
                'currency' => 'Tajikistani Somoni',
                'currency_code' => 'TJS',
                'currency_symbol' => 'ЅM',
                'flag' => '🇹🇯',
            ],
            [
                'name' => 'Tanzania',
                'code' => 'TZ',
                'phone_code' => '+255',
                'currency' => 'Tanzanian Shilling',
                'currency_code' => 'TZS',
                'currency_symbol' => 'TSh',
                'flag' => '🇹🇿',
            ],
            [
                'name' => 'Thailand',
                'code' => 'TH',
                'phone_code' => '+66',
                'currency' => 'Thai Baht',
                'currency_code' => 'THB',
                'currency_symbol' => '฿',
                'flag' => '🇹🇭',
            ],
            [
                'name' => 'Timor-Leste',
                'code' => 'TL',
                'phone_code' => '+670',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇹🇱',
            ],
            [
                'name' => 'Togo',
                'code' => 'TG',
                'phone_code' => '+228',
                'currency' => 'West African CFA franc',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'flag' => '🇹🇬',
            ],
            [
                'name' => 'Tonga',
                'code' => 'TO',
                'phone_code' => '+676',
                'currency' => 'Tongan Paʻanga',
                'currency_code' => 'TOP',
                'currency_symbol' => 'T$',
                'flag' => '🇹🇴',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'code' => 'TT',
                'phone_code' => '+1-868',
                'currency' => 'Trinidad and Tobago Dollar',
                'currency_code' => 'TTD',
                'currency_symbol' => 'TT$',
                'flag' => '🇹🇹',
            ],
            [
                'name' => 'Tunisia',
                'code' => 'TN',
                'phone_code' => '+216',
                'currency' => 'Tunisian Dinar',
                'currency_code' => 'TND',
                'currency_symbol' => 'د.ت',
                'flag' => '🇹🇳',
            ],
            [
                'name' => 'Turkey',
                'code' => 'TR',
                'phone_code' => '+90',
                'currency' => 'Turkish Lira',
                'currency_code' => 'TRY',
                'currency_symbol' => '₺',
                'flag' => '🇹🇷',
            ],
            [
                'name' => 'Turkmenistan',
                'code' => 'TM',
                'phone_code' => '+993',
                'currency' => 'Turkmenistan Manat',
                'currency_code' => 'TMT',
                'currency_symbol' => 'm',
                'flag' => '🇹🇲',
            ],
            [
                'name' => 'Tuvalu',
                'code' => 'TV',
                'phone_code' => '+688',
                'currency' => 'Australian Dollar',
                'currency_code' => 'AUD',
                'currency_symbol' => '$',
                'flag' => '🇹🇻',
            ],
            [
                'name' => 'Uganda',
                'code' => 'UG',
                'phone_code' => '+256',
                'currency' => 'Ugandan Shilling',
                'currency_code' => 'UGX',
                'currency_symbol' => 'USh',
                'flag' => '🇺🇬',
            ],
            [
                'name' => 'Ukraine',
                'code' => 'UA',
                'phone_code' => '+380',
                'currency' => 'Ukrainian Hryvnia',
                'currency_code' => 'UAH',
                'currency_symbol' => '₴',
                'flag' => '🇺🇦',
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'phone_code' => '+971',
                'currency' => 'UAE Dirham',
                'currency_code' => 'AED',
                'currency_symbol' => 'د.إ',
                'flag' => '🇦🇪',
            ],
            [
                'name' => 'United Kingdom',
                'code' => 'GB',
                'phone_code' => '+44',
                'currency' => 'Pound Sterling',
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'flag' => '🇬🇧',
            ],
            [
                'name' => 'United States',
                'code' => 'US',
                'phone_code' => '+1',
                'currency' => 'United States Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇺🇸',
            ],
            [
                'name' => 'Uruguay',
                'code' => 'UY',
                'phone_code' => '+598',
                'currency' => 'Uruguayan Peso',
                'currency_code' => 'UYU',
                'currency_symbol' => '$U',
                'flag' => '🇺🇾',
            ],
            [
                'name' => 'Uzbekistan',
                'code' => 'UZ',
                'phone_code' => '+998',
                'currency' => 'Uzbekistani Soʻm',
                'currency_code' => 'UZS',
                'currency_symbol' => 'soʻm',
                'flag' => '🇺🇿',
            ],
            [
                'name' => 'Vanuatu',
                'code' => 'VU',
                'phone_code' => '+678',
                'currency' => 'Vanuatu Vatu',
                'currency_code' => 'VUV',
                'currency_symbol' => 'VT',
                'flag' => '🇻🇺',
            ],
            [
                'name' => 'Vatican City',
                'code' => 'VA',
                'phone_code' => '+379',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇻🇦',
            ],
            [
                'name' => 'Venezuela',
                'code' => 'VE',
                'phone_code' => '+58',
                'currency' => 'Venezuelan Bolívar',
                'currency_code' => 'VES',
                'currency_symbol' => 'Bs.S',
                'flag' => '🇻🇪',
            ],
            [
                'name' => 'Vietnam',
                'code' => 'VN',
                'phone_code' => '+84',
                'currency' => 'Vietnamese Đồng',
                'currency_code' => 'VND',
                'currency_symbol' => '₫',
                'flag' => '🇻🇳',
            ],
            [
                'name' => 'Yemen',
                'code' => 'YE',
                'phone_code' => '+967',
                'currency' => 'Yemeni Rial',
                'currency_code' => 'YER',
                'currency_symbol' => '﷼',
                'flag' => '🇾🇪',
            ],
            [
                'name' => 'Zambia',
                'code' => 'ZM',
                'phone_code' => '+260',
                'currency' => 'Zambian Kwacha',
                'currency_code' => 'ZMW',
                'currency_symbol' => 'ZK',
                'flag' => '🇿🇲',
            ],
            [
                'name' => 'Zimbabwe',
                'code' => 'ZW',
                'phone_code' => '+263',
                'currency' => 'Zimbabwean Dollar',
                'currency_code' => 'ZWL',
                'currency_symbol' => '$',
                'flag' => '🇿🇼',
            ],
        ];

        \App\Models\Country::insert($countries);
    }
}
