<?php

namespace Database\Seeders;

use App\Models\StateFee;
use Illuminate\Database\Seeder;

class StateFeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $states = [
            [
                'name' => 'Alabama',
                'description' => 'Annual fee for Alabama state registration',
                'amount' => 120.00,
                'renew_amount' => 80.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Online Filing', 'Quick Approval', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alaska',
                'description' => 'Annual fee for Alaska state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['No State Sales Tax', 'Remote Filing', 'Oil Industry Support']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arizona',
                'description' => 'Annual fee for Arizona state registration',
                'amount' => 130.00,
                'renew_amount' => 90.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Low Fees', 'Desert Economy', 'Tech Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arkansas',
                'description' => 'Annual fee for Arkansas state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Affordable Registration', 'Agriculture Focus', 'Online Portal']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'California',
                'description' => 'Annual fee for California state registration',
                'amount' => 200.00,
                'renew_amount' => 150.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tech Hub', 'Strict Compliance', 'Diverse Economy']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colorado',
                'description' => 'Annual fee for Colorado state registration',
                'amount' => 125.00,
                'renew_amount' => 85.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Startup Friendly', 'Online Filing', 'Green Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Connecticut',
                'description' => 'Annual fee for Connecticut state registration',
                'amount' => 140.00,
                'renew_amount' => 100.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Financial Sector', 'Strict Reporting', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delaware',
                'description' => 'Annual fee for Delaware state registration',
                'amount' => 90.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Business Friendly', 'No Sales Tax', 'Fast Incorporation']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Florida',
                'description' => 'Annual fee for Florida state registration',
                'amount' => 150.00,
                'renew_amount' => 100.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tourism Incentives', 'No State Income Tax', 'Online Services']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Georgia',
                'description' => 'Annual fee for Georgia state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Film Industry Support', 'Quick Processing', 'Business Tax Credits']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hawaii',
                'description' => 'Annual fee for Hawaii state registration',
                'amount' => 130.00,
                'renew_amount' => 90.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tourism Focus', 'Island Business Support', 'Online Filing']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Idaho',
                'description' => 'Annual fee for Idaho state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Agriculture Incentives', 'Low Fees', 'Online Portal']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Illinois',
                'description' => 'Annual fee for Illinois state registration',
                'amount' => 160.00,
                'renew_amount' => 120.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Large Market', 'Strict Compliance', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indiana',
                'description' => 'Annual fee for Indiana state registration',
                'amount' => 105.00,
                'renew_amount' => 65.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Manufacturing Hub', 'Online Filing', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iowa',
                'description' => 'Annual fee for Iowa state registration',
                'amount' => 95.00,
                'renew_amount' => 55.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Agriculture Focus', 'Low Fees', 'Quick Approval']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kansas',
                'description' => 'Annual fee for Kansas state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Business Incentives', 'Online Portal', 'Affordable Registration']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kentucky',
                'description' => 'Annual fee for Kentucky state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Manufacturing Support', 'Quick Processing', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Louisiana',
                'description' => 'Annual fee for Louisiana state registration',
                'amount' => 120.00,
                'renew_amount' => 80.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Energy Sector', 'Online Filing', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maine',
                'description' => 'Annual fee for Maine state registration',
                'amount' => 115.00,
                'renew_amount' => 75.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tourism Focus', 'Quick Approval', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maryland',
                'description' => 'Annual fee for Maryland state registration',
                'amount' => 140.00,
                'renew_amount' => 100.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Tech Incentives', 'Online Portal', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Massachusetts',
                'description' => 'Annual fee for Massachusetts state registration',
                'amount' => 170.00,
                'renew_amount' => 130.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Education Hub', 'Strict Compliance', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Michigan',
                'description' => 'Annual fee for Michigan state registration',
                'amount' => 125.00,
                'renew_amount' => 85.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Automotive Industry', 'Online Filing', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minnesota',
                'description' => 'Annual fee for Minnesota state registration',
                'amount' => 130.00,
                'renew_amount' => 90.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Healthcare Focus', 'Quick Approval', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mississippi',
                'description' => 'Annual fee for Mississippi state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Agriculture Focus', 'Online Portal', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Missouri',
                'description' => 'Annual fee for Missouri state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Manufacturing Support', 'Quick Processing', 'Affordable Registration']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Montana',
                'description' => 'Annual fee for Montana state registration',
                'amount' => 105.00,
                'renew_amount' => 65.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['No Sales Tax', 'Online Filing', 'Tourism Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nebraska',
                'description' => 'Annual fee for Nebraska state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Agriculture Focus', 'Quick Approval', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nevada',
                'description' => 'Annual fee for Nevada state registration',
                'amount' => 150.00,
                'renew_amount' => 110.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['No State Income Tax', 'Business Privacy', 'Fast Incorporation']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Hampshire',
                'description' => 'Annual fee for New Hampshire state registration',
                'amount' => 120.00,
                'renew_amount' => 80.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['No Sales Tax', 'Quick Approval', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Jersey',
                'description' => 'Annual fee for New Jersey state registration',
                'amount' => 160.00,
                'renew_amount' => 120.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Large Market', 'Strict Compliance', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Mexico',
                'description' => 'Annual fee for New Mexico state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Low Fees', 'Online Filing', 'Tech Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New York',
                'description' => 'Annual fee for New York state registration',
                'amount' => 200.00,
                'renew_amount' => 150.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Financial Hub', 'Strict Compliance', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'North Carolina',
                'description' => 'Annual fee for North Carolina state registration',
                'amount' => 120.00,
                'renew_amount' => 80.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tech Sector', 'Online Portal', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'North Dakota',
                'description' => 'Annual fee for North Dakota state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Agriculture Focus', 'Quick Approval', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ohio',
                'description' => 'Annual fee for Ohio state registration',
                'amount' => 115.00,
                'renew_amount' => 75.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Manufacturing Hub', 'Online Filing', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oklahoma',
                'description' => 'Annual fee for Oklahoma state registration',
                'amount' => 105.00,
                'renew_amount' => 65.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Energy Sector', 'Quick Processing', 'Affordable Registration']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oregon',
                'description' => 'Annual fee for Oregon state registration',
                'amount' => 130.00,
                'renew_amount' => 90.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Green Business Incentives', 'No Sales Tax', 'Online Portal']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pennsylvania',
                'description' => 'Annual fee for Pennsylvania state registration',
                'amount' => 140.00,
                'renew_amount' => 100.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Large Market', 'Business Grants', 'Online Filing']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rhode Island',
                'description' => 'Annual fee for Rhode Island state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tourism Focus', 'Quick Approval', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Carolina',
                'description' => 'Annual fee for South Carolina state registration',
                'amount' => 120.00,
                'renew_amount' => 80.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Manufacturing Support', 'Online Portal', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Dakota',
                'description' => 'Annual fee for South Dakota state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['No State Income Tax', 'Quick Approval', 'Affordable Registration']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tennessee',
                'description' => 'Annual fee for Tennessee state registration',
                'amount' => 115.00,
                'renew_amount' => 75.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Music Industry Support', 'Online Filing', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Texas',
                'description' => 'Annual fee for Texas state registration',
                'amount' => 150.00,
                'renew_amount' => 110.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['No State Income Tax', 'Large Market', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Utah',
                'description' => 'Annual fee for Utah state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Tech Sector', 'Online Portal', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vermont',
                'description' => 'Annual fee for Vermont state registration',
                'amount' => 105.00,
                'renew_amount' => 65.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tourism Focus', 'Quick Approval', 'Green Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Virginia',
                'description' => 'Annual fee for Virginia state registration',
                'amount' => 130.00,
                'renew_amount' => 90.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Tech Sector', 'Online Filing', 'Business Grants']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Washington',
                'description' => 'Annual fee for Washington state registration',
                'amount' => 140.00,
                'renew_amount' => 100.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Tech Hub', 'No State Income Tax', 'Green Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'West Virginia',
                'description' => 'Annual fee for West Virginia state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Energy Sector', 'Quick Approval', 'Affordable Fees']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wisconsin',
                'description' => 'Annual fee for Wisconsin state registration',
                'amount' => 110.00,
                'renew_amount' => 70.00,
                'status' => true,
                'auto_renew' => false,
                'features' => json_encode(['Manufacturing Hub', 'Online Portal', 'Business Incentives']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wyoming',
                'description' => 'Annual fee for Wyoming state registration',
                'amount' => 100.00,
                'renew_amount' => 60.00,
                'status' => true,
                'auto_renew' => true,
                'features' => json_encode(['Most Affordable', 'Fast Processing', 'No Hidden Fees', 'No Annual Report Required']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        StateFee::insert($states);
    }
}
