@extends('layouts.fontpage')

@section('title', 'Privacy Policy')

@push('styles')
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" />

<style>
    .simple-transparent {
        font-size: 35px;
        letter-spacing: -0.06em;
        line-height: 58px;
        font-weight: 500;
        font-family: Poppins;
        color: #080808;
        text-align: center;
        margin:0px auto;
    }
   .welcome-to-expedite {
        margin: 0;
        font-weight: 600;
    }
    .expedite-formation-us {
        margin: 0;
    }
    .welcome-to-expedite-container {
        position: relative;
        font-size: 14px;
        letter-spacing: -0.02em;
        line-height: 156.5%;
        color: #4b4b4b;
        text-align: justify;
        opacity: 0.8;
        font-family: Poppins;
        border: 1px solid #0000001f;
        padding: 14px;
        border-radius: 15px;
    }


</style>

@endpush


@section('content')
<div class="container mt-5">
    <div class="simple-transparent">Privacy policy</div>
    <hr>
</div>
<div class="container mt-5 mb-5 pb-5">

    <div class="welcome-to-expedite-container">
        <p class="welcome-to-expedite">Welcome to Expedite Formation.</p>
        <p class="expedite-formation-us">Expedite Formation  (“us,” “we,” or “our”) operates at https://expediteformation.com/ (hereinafter referred to as “Service”).</p>
        <p class="expedite-formation-us">Our Privacy Policy governs your visit to expediteformation.com and explains how we collect, safeguard, and disclose information that results from your use of our service.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">We use your data to provide and improve Service. By using the Service, you agree to collect and use information following this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
        <p class="expedite-formation-us">Our Terms and Conditions (“Terms”) govern all use of our Service and, together with the Privacy Policy, constitute your agreement with us (“Agreement”).</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Definitions</p>
        <p class="expedite-formation-us">SERVICE means the expediteformation.com website operated by Expedite Formation.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">USAGE DATA is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">COOKIES are small files stored on your device (computer or mobile device).</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">DATA CONTROLLER means a natural or legal person who (alone or jointly or in common with other persons) determines the purposes for which and how personal data are processed or are to be. For this Privacy Policy, we are a Data Controller of your data.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers to process your data more effectively.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
        <p class="expedite-formation-us">THE USER is the individual using our Service. The User corresponds to the Data Subject, the subject of Personal Data.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Information Collection and Use</p>
        <p class="expedite-formation-us">We collect various types of information to provide and improve our Service.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Types of Data We Collect</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Personal Information</p>
        <p class="expedite-formation-us">While using our Service, we will ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.1. Email address</p>
        <p class="expedite-formation-us">0.2. First name and last name</p>
        <p class="expedite-formation-us">0.3. Phone number</p>
        <p class="expedite-formation-us">0.4. Address, Country, State, Province, ZIP/Postal code, City</p>
        <p class="expedite-formation-us">0.5. Cookies and Usage Data</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">We may use your Data to contact you with newsletters, marketing or promotional materials, and other information that may interest you. You may opt out of receiving any or all of these communications from us by following the unsubscribe link.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Usage Data</p>
        <p class="expedite-formation-us">We may also collect information that your browser sends whenever you visit our Service or access the Service by or through any device (“Usage Data”).</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">This Usage Data may include information such as your computer’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p class="expedite-formation-us">When you access Service with a device, this Usage Data may include information such as the type of device you use, your unique device ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Location Data</p>
        <p class="expedite-formation-us">We may use and store information about your location if you permit us to do so (“Location Data”). We use this data to provide our Service's features and improve and customize our Service.</p>
        <p class="expedite-formation-us">You can enable or disable location services using our Service anytime through your device settings.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Tracking Cookies Data</p>
        <p class="expedite-formation-us">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
        <p class="expedite-formation-us">Cookies are files with a small amount of data which may include a unique anonymous identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies such as beacons, tags, and scripts are also used to collect and track information and to improve and analyze our Service.</p>
        <p class="expedite-formation-us">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may be unable to use some portions of our Service.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Examples of Cookies we use:</p>
        <p class="expedite-formation-us">0.1. Session Cookies: We use Session Cookies to operate our Service.</p>
        <p class="expedite-formation-us">0.2. Preference Cookies: We use Preference Cookies to remember your preferences and settings.</p>
        <p class="expedite-formation-us">0.3. Security Cookies: We use Security Cookies for security purposes.</p>
        <p class="expedite-formation-us">0.4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Other Data</p>
        <p class="expedite-formation-us">While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at the site of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location, and other data.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Use of Data</p>
        <p class="expedite-formation-us">Expedite Formation uses the collected data for various purposes, including:</p>
        <p class="expedite-formation-us">0.1. to provide and maintain our Service;</p>
        <p class="expedite-formation-us">0.2. to notify you about changes to our Service;</p>
        <p class="expedite-formation-us">0.3. to allow you to participate in interactive features of our Service when you choose to do so;</p>
        <p class="expedite-formation-us">0.4. to provide customer support;</p>
        <p class="expedite-formation-us">0.5. to gather analysis or valuable information so that we can improve our Service;</p>
        <p class="expedite-formation-us">0.6. to monitor the usage of our Service;</p>
        <p class="expedite-formation-us">0.7. to detect, prevent, and address technical issues;</p>
        <p class="expedite-formation-us">0.8. to fulfill any other purpose for which you provide it;</p>
        <p class="expedite-formation-us">0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</p>
        <p class="expedite-formation-us">0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.;</p>
        <p class="expedite-formation-us">0.11. to provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information,</p>
        <p class="expedite-formation-us">0.12. in any other way, we may describe when you provide the information;</p>
        <p class="expedite-formation-us">0.13. for any other purpose with your consent.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Retention of Data</p>
        <p class="expedite-formation-us">We will retain your Data only for as long as necessary for the purposes in this Privacy Policy. We will retain and use your Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p class="expedite-formation-us">Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or improve the functionality of our Service. We are legally obligated to retain this data for more extended periods. We will also have Usage Data for internal analysis purposes.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Transfer of Data</p>
        <p class="expedite-formation-us">Your information, including Personal Data, may be transferred to – and maintained on – computers outside your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p class="expedite-formation-us">If you are located outside the USA and choose to provide information to us, please note that we transfer the data, including Personal Data, to the USA and process it there.</p>
        <p class="expedite-formation-us">Your consent to this Privacy Policy, followed by submitting such information, represents your agreement to that transfer.</p>
        <p class="expedite-formation-us">Expedite Formation will take all the steps reasonably necessary to ensure that your data is treated securely and following this Privacy Policy. No transfer of your Personal Data will occur to an organization or country unless adequate controls exist, including the security of your data and other personal information.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Disclosure of Data</p>
        <p class="expedite-formation-us">We may disclose personal information that we collect or that you provide for us:</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.1. Disclosure for Law Enforcement</p>
        <p class="expedite-formation-us">Under certain circumstances, we may be required to disclose your Data if required by law or in response to valid requests by public authorities.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.2. Business Transaction</p>
        <p class="expedite-formation-us">Your personal data may be transferred if our subsidiaries or we are involved in a merger, acquisition, or asset sale.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.3. Other cases: We may also disclose your information:</p>
        <p class="expedite-formation-us">0.3.1. to our subsidiaries and affiliates;</p>
        <p class="expedite-formation-us">0.3.2. to contractors, service providers, and other third parties we use to support our business;</p>
        <p class="expedite-formation-us">0.3.3. to fulfill the purpose for which you provide it;</p>
        <p class="expedite-formation-us">0.3.4. to include your Company’s logo on our website;</p>
        <p class="expedite-formation-us">0.3.5. for any other purpose disclosed by us when you provide the information;</p>
        <p class="expedite-formation-us">0.3.6. with your consent in any other cases;</p>
        <p class="expedite-formation-us">0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Security of Data</p>
        <p class="expedite-formation-us">The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its security.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Your Data Protection Rights Under the General Data Protection Regulation (GDPR)</p>
        <p class="expedite-formation-us">If you are a European Union (EU) and European Economic Area (EEA) resident, you have certain data protection rights covered by GDPR.</p>
        <p class="expedite-formation-us">We take reasonable steps to allow you to correct, amend, delete, or limit your personal data use.</p>
        <p class="expedite-formation-us">If you wish to inform us what Personal Data we hold about you and if you want it removed from our systems, please email us at info@expediteformation.com.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">In certain circumstances, you have the following data protection rights:</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.1. The right to access, update, or delete the information we have on you;</p>
        <p class="expedite-formation-us">0.2. The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</p>
        <p class="expedite-formation-us">0.3. The right to object. You have the right to object to our processing of your Personal Data;</p>
        <p class="expedite-formation-us">0.4. The right of restriction. You have the right to request that we restrict the processing of your personal information;</p>
        <p class="expedite-formation-us">0.5. The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable, and commonly used format;</p>
        <p class="expedite-formation-us">0.6. The right to withdraw consent. You also have the right to withdraw your consent at any time when we rely on your support to process your personal information;</p>
        <p class="expedite-formation-us">Please note that we may ask you to verify your identity before responding to such requests. Please note we may not be able to provide Service without some necessary data.</p>
        <p class="expedite-formation-us">You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. Please contact your local European Economic Area (EEA) data protection authority for more information.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</p>
        <p class="expedite-formation-us">CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or Company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating precisely the data being collected and those individuals with whom it is being shared and to comply with this policy.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">According to CalOPPA, we agree to the following:</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.1. users can visit our site anonymously;</p>
        <p class="expedite-formation-us">0.2. our Privacy Policy link includes the word “Privacy” and can easily be found on the homepage of our website;</p>
        <p class="expedite-formation-us">0.3. users will be notified of any privacy policy changes on our Privacy Policy Page;</p>
        <p class="expedite-formation-us">0.4. users can change their personal information by emailing us at info@expediteformation.com.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Our Policy on “Do Not Track” Signals</p>
        <p class="expedite-formation-us">We honor Do Not Track signals and do not track plant cookies or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
        <p class="expedite-formation-us">You can enable or disable Do Not Track by visiting your web browser's Preferences or Settings page.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</p>
        <p class="expedite-formation-us">If you are a California resident, you can learn what data we collect about you, ask to delete your data, and not sell (share) it. To exercise your data protection rights, you can make specific requests and ask us:</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">0.1. What personal information do we have about you? If you make this request, we will return to you:</p>
        <p class="expedite-formation-us">0.0.1. The categories of personal information we have collected about you.</p>
        <p class="expedite-formation-us">0.0.2. The categories of sources from which we collect your personal information.</p>
        <p class="expedite-formation-us">0.0.3. The business or commercial purpose for collecting or selling personal information.</p>
        <p class="expedite-formation-us">0.0.4. The categories of third parties with whom we share personal information.</p>
        <p class="expedite-formation-us">0.0.5. The specific pieces of personal information we have collected about you.</p>
        <p class="expedite-formation-us">0.0.6. A list of categories of personal information we have sold and the variety of any other company we sold it to. If we have yet to sell your data, we will inform you.</p>
        <p class="expedite-formation-us">0.0.7. A list of categories of personal information that we have disclosed for a business purpose, along with the variety of any other company we shared it with.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Please note you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">To delete your personal information: If you make this request, we will delete the personal information we hold from our records and direct service providers to do the same. De-identifying the data may be a solution in some circumstances. If you delete your personal information, you may be unable to use certain functions that require your input.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">To stop selling your personal information: We Don’t sell or rent your personal information to any third parties for any purpose. You are the only data owner and can request disclosure or deletion anytime. We do not sell your data for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without financial review may be considered a “sale” under California law.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">If you submit a request to stop selling your personal information, we will stop making such transfers.</p>
        <p class="expedite-formation-us">Please note that if you ask us to delete or stop selling your data, it may impact your experience with us. You may not be able to participate in specific programs or membership services that require using your personal information to function. But in no circumstances will we discriminate against you for exercising your rights.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">To exercise your California data protection rights described above, please email your request(s): to info@expediteformation.com.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. The CCPA took effect on 01/01/2020. To find out more, visit the official California Legislative Information website.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Service Providers</p>
        <p class="expedite-formation-us">We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.</p>
        <p class="expedite-formation-us">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        <p class="expedite-formation-us">&nbsp;</p>
        <p class="expedite-formation-us">Analytics</p>
        <p class="expedite-formation-us">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">CI/CD tools</p>
        <p class="expedite-formation-us">We may use third-party service Providers to automate the development process of our Service.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Advertising</p>
        <p class="expedite-formation-us">We may use third-party Service Providers to show advertisements to you to help support and maintain our service.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Behavioral Remarketing</p>
        <p class="expedite-formation-us">We may use remarketing services to advertise on third-party websites after you visit our Service. Our third-party vendors and we use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Payments</p>
        <p class="expedite-formation-us">We may provide paid products and services within Service. In that case, we use third-party services for payment processing (e.g., payment processors).</p>
        <p class="expedite-formation-us">We won't store or collect your payment details. That information is provided directly to our third-party payment processors, governed by their Privacy Policy. These processors adhere to PCI-DSS, a joint effort of brands like Visa, Mastercard, and Discover. PCI-DSS requirements help ensure the handling of payment information.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Links to Other Sites</p>
        <p class="expedite-formation-us">Our service may contain links to other sites that we do not operate. You will be directed to that site if you click a third-party link. We strongly advise you to review every site's privacy policy.</p>
        <p class="expedite-formation-us">We have no control over and assume no responsibility for any third-party sites or services' content, privacy policies, or practices.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Children’s Privacy</p>
        <p class="expedite-formation-us">Our services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>
        <p class="expedite-formation-us">We do not knowingly collect personally identifiable information from children under 18. Please contact us if a child has provided us with personal data. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Changes to This Privacy Policy</p>
        <p class="expedite-formation-us">We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page.</p>
        <p class="expedite-formation-us">We will inform you via email and/or a prominent notice on our service before the change becomes effective and update the “effective date” at the top of this privacy policy.</p>
        <p class="expedite-formation-us">You are advised to review this privacy policy periodically for any changes. These privacy policy changes are effective when posted on this page.</p>
        <p class="expedite-formation-us"> </p>
        <p class="expedite-formation-us">Contact Us</p>
        <p class="expedite-formation-us">If you have questions about this privacy policy, please contact us by email at info@expediteformation.com.</p>
    </div>


</div>


@endsection


@push('scripts')



@endpush